using System.Net;
using System.Text;
using WinUpdateChecker.Core.Models;

namespace WinUpdateChecker.Core.Export;

/// <summary>Stand-alone styled HTML report (light/dark aware), ported from v1 Export-HtmlReport.</summary>
public static class HtmlExporter
{
    public static string Render(IReadOnlyList<ReportRow> rows)
    {
        var generated = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
        var availableCount = rows.Count(r => r.IsUpdate);

        var rowsHtml = new StringBuilder();
        foreach (var r in rows)
        {
            var cls = r.IsUpdate ? "update" : "ok";
            rowsHtml.AppendLine(
                $"<tr class='{cls}'><td>{E(r.Name)}</td><td>{E(r.Publisher)}</td><td>{E(r.Current)}</td>" +
                $"<td>{E(r.Available)}</td><td>{E(r.Status)}</td><td>{E(r.PackageId)}</td><td>{E(r.PackageSource)}</td></tr>");
        }

        return $$"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>{{AppInfo.ProductName}} Report</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; margin: 2rem; max-width: 1300px; }
  h1 { margin: 0 0 0.25rem; }
  .meta { color: #666; margin-bottom: 1.5rem; font-size: 0.9rem; }
  .summary { display: flex; gap: 1rem; margin-bottom: 1.5rem; }
  .card { padding: 0.75rem 1.25rem; border-radius: 6px; background: #f4f4f7; border: 1px solid #ddd; }
  .card.warn { background: #fff7d6; border-color: #e0c870; }
  table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
  th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid #e5e5e5; }
  th { background: #f0f0f5; position: sticky; top: 0; }
  tr.update { background: #fffbe6; }
  tr.update td:nth-child(5) { color: #b06a00; font-weight: 600; }
  tbody tr:hover { background: #f7f7fb; }
  footer { margin-top: 2rem; color: #888; font-size: 0.8rem; }
  @media (prefers-color-scheme: dark) {
    body { background: #1a1a1d; color: #e8e8e8; }
    .card { background: #25252b; border-color: #38383f; }
    .card.warn { background: #3a3422; border-color: #6b5d2a; }
    th { background: #25252b; }
    th, td { border-color: #2e2e34; }
    tr.update { background: #2e2820; }
    tr.update td:nth-child(5) { color: #f0c060; }
    tbody tr:hover { background: #28282e; }
  }
</style>
</head>
<body>
<h1>{{AppInfo.ProductName}} Report</h1>
<div class="meta">Generated {{generated}} &middot; v{{AppInfo.Version}}</div>
<div class="summary">
  <div class="card warn"><strong>{{availableCount}}</strong> updates available</div>
  <div class="card"><strong>{{rows.Count}}</strong> programs scanned</div>
</div>
<table>
  <thead>
    <tr><th>Name</th><th>Publisher</th><th>Current</th><th>Available</th><th>Status</th><th>Package Id</th><th>Source</th></tr>
  </thead>
  <tbody>
{{rowsHtml.ToString()}}
  </tbody>
</table>
<footer>
  Generated by <a href="{{AppInfo.RepoUrl}}">{{AppInfo.ProductName}}</a>.
</footer>
</body>
</html>
""";
    }

    public static void Write(IReadOnlyList<ReportRow> rows, string path)
        => File.WriteAllText(path, Render(rows), Encoding.UTF8);

    private static string E(string? text) => WebUtility.HtmlEncode(text ?? "");
}
