<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WinUpdateChecker.Core\WinUpdateChecker.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <StartupObject>WinUpdateChecker.App.Program</StartupObject>
    <AssemblyName>WinUpdateChecker</AssemblyName>
  </PropertyGroup>

</Project>
